### ISSUE TITLE
funding_sources and credit fields in the identity group?

### ISSUE THREAD

**Issue by smXplorer** [Photon-HDF5/photon-hdf5#21]
Reading the manuscript, I feel that we should provide further information related to funding source and how to credit the work. Possibly even acknowledgments (when the author is not the only one involved).

**Comment by tritemio** [comment]
We can always add more fields like `funding` and if you wish `acknowledgements`.

Citation cannot be enforced,as with publications is just common courtesy. The file already has URL and DOI. If you want to suggest a preferred way of citation, this should be prominently placed in the hosting website (e.g. figshare) not hidden inside the file, where nobody will see it.

For me the preferred citation is the first publication where the data is presented. The second option is the DOI of the deposited data file. Since you publish the data first, then the paper, I don't see it practical  to embed the citation preferences. I'm not even sure you can preserve the DOI if you change the data file.

Finally, we may want to add a new `license` field. While data under US (and most other countries) law cannot have copyright, it can have a license. We advocate for CC0 (aka public domain) license (as customary and also required in most cases) but we will cover also other corner cases where data has restrictions.
